In [30]:
import pandas as pd
from gensim.models import Word2Vec
import re
from nltk.stem import SnowballStemmer, WordNetLemmatizer
stemmer = SnowballStemmer('english')
import nltk
nltk.download('wordnet')
import numpy as np
lemmatizer = WordNetLemmatizer()


[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/gigimancinelli./nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [31]:
criminality = ['theft', 'deviance', 'indictment', 'criminalization', 'guilt', 'government', 'tort', 
               'criminalness', 'criminalism', 'imprisonment', 'punishment', 'law', 'banditry', 'lawlessness', 
               'statutory', 'illegality', 'murder', 'immorality', 'sectarianism', 'dishonesty', 
               'impunity', 'criminalisation', 'brutality', 'thuggery', 'trial', 'recklessness', 'militancy', 
               'decriminalization', 'sentence', 'bigotry', 'extremism', 'viciousness', 'duplicity', 
               'xenophobia', 'mysonygy', 'stupidity', 'hypocrisy', 'irresponsibility', 'racism',
               'illegalities', 'coercion', 'vigilantism', 'imprisonment', 'plaintiff', 'criminology', 
               'felony', 'desertion', 'charge', 'power', 'wrong']
mental = ['schizophrenia', 'depression', 'bipolar', 'disorder', 'antisocial', 'personality', 'psychosis', 
          'psychotherapy', 'dementia', 'psychopathy', 'disability', 'anxiety', 'illness', 'alcoholism', 'brain', 
          'diagnosis', 'mind', 'symptoms', 'delusions', 'hallucinations', 'chronic', 'attention', 'deficit', 
          'hyperactivity', 'psychiatrists', 'disease', 'stress', 'epilepsy', 'agoraphobia', 'suffering', 
          'dysthymia', 'hypomania', 'sclerosis', 'psychiatric', 'psychological', 'disabilities', 'paraphilia', 
          'ocd', 'psychotic', 'syndrome', 'delusional', 'community', 'eating', 'disorder', 'anorexia', 'bulimia', 
          'nervosa', 'sickness', 'substance', 'abuse']

In [32]:
len(criminality)

50

In [33]:
len(mental)

50

In [34]:
model = Word2Vec.load("./model/word2vec.model")

In [35]:
df = pd.read_csv("./data/mpv_clean_pattern_stop.csv")

In [36]:
df.head()

Unnamed: 0            name gender   race   age        date  after_Floyd  \
0           0  Clyde E. Young   Male  White  28.0  2024-02-22         True   
1           1  Clyde E. Young   Male  White  28.0  2024-02-22         True   
2           2  Jamarcus Brown   Male  Black  35.0  2024-02-21         True   
3           3  Jamarcus Brown   Male  Black  35.0  2024-02-21         True   
4           4  Jamarcus Brown   Male  Black  35.0  2024-02-21         True   

             city state cause_of_death  ... wapo_armed wapo_threat_level  \
0      West Alton    MO        Gunshot  ...        NaN       Used Weapon   
1      West Alton    MO        Gunshot  ...        NaN       Used Weapon   
2  Lake Cormorant    MS        Gunshot  ...        NaN            Attack   
3  Lake Cormorant    MS        Gunshot  ...        NaN            Attack   
4  Lake Cormorant    MS        Gunshot  ...        NaN            Attack   

     wapo_flee            wapo_body_camera    initial_reason  \
0  Not Fleeing                         NaN  Murder (suspect)   
1  Not Fleeing                         NaN  Murder (suspect)   
2          Car  Victim Facebook Live Video      Traffic Stop   
3          Car  Victim Facebook Live Video      Traffic Stop   
4          Car  Victim Facebook Live Video      Traffic Stop   

                                                text  \
0  ['A Godfrey man who had been charged with murd...   
1  ['The man, identified as Clyde Young, was char...   
2  ['DESOTO COUNTY, Miss. (WMC) - Mississippi Bur...   
3  ['Close Get email notifications on {{subject}}...   
4  ['The Carlos Moore Law Group said it has been ...   

                      authors  \
0     [['Mike Koziatek'], []]   
1     [['Mike Koziatek'], []]   
2  [[], ['Lakiya Scott'], []]   
3  [[], ['Lakiya Scott'], []]   
4  [[], ['Lakiya Scott'], []]   

                                          TextColumn  \
0    a godfrey man who had been charged with murd...   
1    the man  identified as clyde young  was char...   
2    desoto county  miss   wmc    mississippi bur...   
3    close get email notifications on   subject  ...   
4    the carlos moore law group said it has been ...   

                                             cleaned  \
0  godfrey man who had been charged with murder i...   
1  the man identified as clyde young was charged ...   
2  desoto county miss wmc mississippi bureau of i...   
3  close get on subject are only sent and only if...   
4  the carlos moore law group said it has been re...   

                                           sentences  
0  [['godfrey', 'man', 'charged', 'murder', 'shoo...  
1  [['man', 'identified', 'clyde', 'young', 'char...  
2  [['desoto', 'county', 'miss', 'wmc', 'mississi...  
3       [['close', 'get', 'subject', 'sent', 'new']]  
4  [['carlos', 'moore', 'law', 'group', 'said', '...  

[5 rows x 25 columns]

In [37]:
def create_embedding(text):
    text = re.sub(r'[^a-zA-Z0-9]', ' ', text)
    text = text.strip()
    embeddings = [model.wv[word] for word in text.split()]
    if len(embeddings) == 0:
        return 0
    emb = sum(embeddings) / len(embeddings)
    return emb

In [38]:
df['emb'] = df['sentences'].apply(create_embedding)

In [39]:
df.columns

Index(['Unnamed: 0', 'name', 'gender', 'race', 'age', 'date', 'after_Floyd',
       'city', 'state', 'cause_of_death', 'circumstances', 'news_urls',
       'signs_of_mental_illness', 'officer_charged', 'allegedly_armed',
       'wapo_armed', 'wapo_threat_level', 'wapo_flee', 'wapo_body_camera',
       'initial_reason', 'text', 'authors', 'TextColumn', 'cleaned',
       'sentences', 'emb'],
      dtype='object')

In [40]:
df.allegedly_armed.unique()

array(['Allegedly Armed', 'Unarmed/Did Not Have Actual Weapon', 'Vehicle',
       'Unclear'], dtype=object)

In [41]:
df.iloc[0].emb

array([ 0.05998774, -0.20063488, -0.20840636,  0.42882782, -0.3586672 ,
        0.52818817, -0.99431676, -0.19250348, -0.28659242, -0.79211706,
       -0.08631368,  0.2544588 ,  0.06359314,  0.2672201 ,  0.24754508,
        0.62931937,  0.09819652, -0.87627584, -0.06199381,  0.14154018,
        0.11312877, -0.135405  ,  0.2820805 ,  0.06137591,  0.15564716,
       -0.0066459 ,  0.16089754, -0.06620071,  0.01037197, -0.57633185,
       -0.07710057,  0.02693513, -0.779873  ,  0.20013641, -0.2527932 ,
       -0.12801911,  0.44330087, -0.09281491, -0.07654728,  0.5051678 ,
        0.3762602 , -0.0356443 ,  0.11734853,  0.19492012,  0.04742831,
        0.1107235 ,  0.20942263,  0.78091925,  0.33039868, -0.28148937,
       -0.17023821, -0.9795949 , -0.04677298, -0.06564026,  0.0659398 ,
       -0.23979445,  0.1740262 , -0.06163668, -0.15633774,  0.03280338,
        0.9341486 , -0.6513728 ,  0.4060313 ,  0.22546786,  0.29005444,
       -0.04230206, -0.3447351 , -0.31954864, -0.39408946,  0.26

In [42]:
def create_embedding_dimension_lem(l):
    lemmatized = [lemmatizer.lemmatize(w) for w in l] 
    embeddings = [model.wv[word] for word in lemmatized if word in model.wv]
    if len(embeddings) == 0:
        return 0
    emb = sum(embeddings) / len(embeddings)
    return emb

In [43]:
def create_embedding_dimension(l):
    stemmed = [stemmer.stem(w) for w in l] 
    embeddings = [model.wv[word] for word in stemmed if word in model.wv]
    if len(embeddings) == 0:
        return 0
    emb = sum(embeddings) / len(embeddings)
    return emb

In [44]:
criminal_dimension = create_embedding_dimension(criminality)
mental_dimension = create_embedding_dimension(mental)

In [45]:
criminal_dimension_lem = create_embedding_dimension_lem(criminality)
mental_dimension_lem = create_embedding_dimension_lem(mental)

In [46]:
criminal_dimension

array([ 0.11721932, -0.06764658, -0.28589466, -0.08733147, -0.22453795,
        0.07069158,  0.2892608 ,  0.03640572, -0.06961068, -0.4129686 ,
       -0.05707993,  0.12199292, -0.03294465,  0.42207068,  0.05815085,
        0.3228303 , -0.03553088,  0.02358142,  0.00740328,  0.03457382,
        0.10332633, -0.02411895,  0.17559743,  0.02518764,  0.07132082,
       -0.17920756, -0.40039024, -0.06093131, -0.16439086, -0.07058294,
       -0.170402  , -0.37967595, -0.4211788 ,  0.07650433, -0.10783713,
       -0.19327496,  0.10211004, -0.45417204, -0.07899039,  0.5804341 ,
       -0.04900618,  0.40223005, -0.0292807 ,  0.14829189, -0.06468523,
        0.23752333,  0.12846564,  0.6096768 ,  0.08340271, -0.03652385,
       -0.35800597, -0.40902603,  0.05472304,  0.09642358, -0.16635561,
        0.02288793,  0.07346623,  0.14990452, -0.24925962,  0.14046244,
        0.12299076, -0.131125  , -0.3425527 ,  0.6038035 ,  0.47530028,
        0.25739834,  0.32766712, -0.23106594,  0.04771752, -0.41

In [47]:
mental_dimension

array([-0.08880261,  0.34311453, -0.330107  ,  0.4938667 , -0.5023755 ,
        0.7234274 ,  0.25932205,  0.19696194,  0.29590568, -0.19861807,
       -0.29497552,  0.16225001, -0.25805357,  0.06050476, -0.06246739,
       -0.40452784, -0.13958782, -0.04190193, -0.3581606 ,  0.00507286,
       -0.20578794,  0.14817002,  0.03508539,  0.49019995, -0.19084097,
       -0.0648149 , -0.34999377, -0.38513958,  0.06200857, -0.03797945,
       -0.17131586, -0.5450354 ,  0.06857347, -0.09761941, -0.2788764 ,
       -0.09158283,  0.13576767, -0.31333932,  0.18543482,  0.3995957 ,
        0.1643513 ,  0.06682139,  0.2790651 , -0.03052558,  0.14965892,
       -0.1609004 , -0.13813625, -0.00913812,  0.2521182 , -0.27209955,
       -0.32723093, -0.56304955,  0.30025145,  0.12998666, -0.18723886,
        0.1082688 , -0.39359912,  0.22956038,  0.01355254,  0.140231  ,
        0.04520568,  0.08961362,  0.16391478,  0.27980113,  0.13841021,
        0.12691748,  0.47324723,  0.02617019,  0.12494875, -0.10

In [48]:
def cosine_similarity(v1, v2):
    dot_ = np.dot(v1, v2)
    norm1 = np.linalg.norm(v1)
    norm2 = np.linalg.norm(v2)
    if norm1 > 0 and norm2 > 0:
        return dot_ / (norm1 * norm2)
    else:
        return 0.0

In [49]:
cosine_similarity(criminal_dimension, mental_dimension)

0.445961

In [50]:
cosine_similarity(criminal_dimension_lem, mental_dimension_lem)

0.43741024

In [51]:
df['cosine_criminal'] = df['emb'].apply(lambda x: cosine_similarity(criminal_dimension, x))
df['cosine_mental'] = df['emb'].apply(lambda x: cosine_similarity(mental_dimension, x))

In [52]:
df['cosine_criminal_lem'] = df['emb'].apply(lambda x: cosine_similarity(criminal_dimension_lem, x))
df['cosine_mental_lem'] = df['emb'].apply(lambda x: cosine_similarity(mental_dimension_lem, x))

In [53]:
average_criminal_white = df[df.race == 'White'].cosine_criminal.sum() / len(df[df.race == 'White'])
average_criminal_black = df[df.race == 'Black'].cosine_criminal.sum() / len(df[df.race == 'Black'])
average_mental_white = df[df.race == 'White'].cosine_mental.sum() / len(df[df.race == 'White'])
average_mental_black = df[df.race == 'Black'].cosine_mental.sum() / len(df[df.race == 'Black'])

print(average_criminal_white)
print(average_criminal_black)
print(average_mental_white)
print(average_mental_black)

0.33771991847534216
0.3651912728764902
0.1331491219929558
0.15749283921623664


In [54]:
average_criminal_white_lem = df[df.race == 'White'].cosine_criminal_lem.sum() / len(df[df.race == 'White'])
average_criminal_black_lem = df[df.race == 'Black'].cosine_criminal_lem.sum() / len(df[df.race == 'Black'])
average_mental_white_lem = df[df.race == 'White'].cosine_mental_lem.sum() / len(df[df.race == 'White'])
average_mental_black_lem = df[df.race == 'Black'].cosine_mental_lem.sum() / len(df[df.race == 'Black'])

print(average_criminal_white_lem)
print(average_criminal_black_lem)
print(average_mental_white_lem)
print(average_mental_black_lem)

0.30350422784957515
0.32698407355959785
0.031597853418508105
0.05010262698434999


In [55]:
def extract_sign_mental(col):
    if col == 'Yes' or col == 'Drug or Alcohol Use' or col == 'History of Drug or Alcohol Use':
        return 1
    else:
        return 0
    
def extract_sign_armed(col):
    if col == 'Allegedly Armed' or col == 'Vehicle':
        return 1
    else:
        return 0

In [56]:
df['mental'] = df['signs_of_mental_illness'].apply(extract_sign_mental)
df['criminal'] = df['allegedly_armed'].apply(extract_sign_armed)

In [57]:
proxy_criminal_white = df[df.race == 'White'].criminal.sum() / len(df[df.race == 'White'])
proxy_criminal_black = df[df.race == 'Black'].criminal.sum() / len(df[df.race == 'Black'])
proxy_mental_white = df[df.race == 'White'].mental.sum() / len(df[df.race == 'White'])
proxy_mental_black = df[df.race == 'Black'].mental.sum() / len(df[df.race == 'Black'])

In [58]:
print(proxy_criminal_white)
print(proxy_criminal_black)
print(proxy_mental_white)
print(proxy_mental_black)

0.7954462659380692
0.7124600638977636
0.3604735883424408
0.2292332268370607


In [59]:
print(f"Proportion of white victims armed: {proxy_criminal_white}. Criminal bias in articles for white victims: {average_criminal_white}")
print(f"Proportion of black victims armed: {proxy_criminal_black}. Criminal bias in articles for black victims: {average_criminal_black}")
print(f"Proportion of white victims with signs of mental illness: {proxy_mental_white}. Mental bias in articles for white victims: {average_mental_white}")
print(f"Proportion of black victims with signs of mental illness: {proxy_mental_black}. Mental bias in articles for black victims: {average_mental_black}")

Proportion of white victims armed: 0.7954462659380692. Criminal bias in articles for white victims: 0.33771991847534216
Proportion of black victims armed: 0.7124600638977636. Criminal bias in articles for black victims: 0.3651912728764902
Proportion of white victims with signs of mental illness: 0.3604735883424408. Mental bias in articles for white victims: 0.1331491219929558
Proportion of black victims with signs of mental illness: 0.2292332268370607. Mental bias in articles for black victims: 0.15749283921623664
